name: Deploy to production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          coverage: xdebug

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Generate Ziggy routes
        run: php artisan ziggy:generate resources/js/ziggy.js

      - name: Install Node dependencies
        run: npm ci --legacy-peer-deps

      - name: Build assets
        run: npm run build
      
      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          passphrase: ${{ secrets.PROD_PASSPHRASE }}
          source: "public/build"
          target: "/var/www/cetakcerdas.com"

      # - name: Upload ssr to server
      #   uses: appleboy/scp-action@v0.1.7
      #   with:
      #     host: ${{ secrets.PROD_HOST }}
      #     username: ${{ secrets.PROD_USER }}
      #     key: ${{ secrets.PROD_PRIVATE_KEY }}
      #     passphrase: ${{ secrets.PROD_PASSPHRASE }}
      #     source: "bootstrap/ssr"
      #     target: "/var/www/cetakcerdas.com"
        
      - name: Tests
        run: php artisan test

      - name: SSH and deploy backend
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_PRIVATE_KEY }}
          passphrase: ${{ secrets.PROD_PASSPHRASE }}
          script: |
            cd /var/www/cetakcerdas.com
            sudo chown -R $(whoami):$(whoami) storage bootstrap/cache .git
            sudo chmod -R 775 storage bootstrap/cache
            git pull origin main
            composer install --no-dev --optimize-autoloader
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize

